### PR TITLE
adding post-CTF data

### PR DESCRIPTION
**Pull request by bsidestlvctf**

### CODE REVIEW

**Comment by omercnet** [comment]
@bsidestlvctf please place the large pdf in the static repo to avoid blowing up this one

**Review by omercnet — CHANGES_REQUESTED** [review]
Move pdf to static repo

**Comment by bsidestlvctf** [comment]
> 

Statis repo? do you have a link or something? not familiar with it

**Comment by omercnet** [comment]
https://github.com/bsidestlv/static.bsidestlv.com

**Comment by bsidestlvctf** [comment]
@omercnet done

**Review by omercnet — APPROVED** [review]

**Pull request merged**
