### PR TITLE
round 1

### PR DESCRIPTION
**Pull request by xFreed0m**
GE - Platinum
Cymru - Bronze
Cymotiv - Silver
Salesforce - Gold
Intel - Gold
PAN - Gold
*Moonactive - Silver

### CODE REVIEW

**Review by omercnet — CHANGES_REQUESTED** [review]
few logos are missing, please run this locally to confirm things looks good before opening a PR

**Comment by xFreed0m** [comment]
> few logos are missing, please run this locally to confirm things looks good before opening a PR

We know some are missing, that's why only some appear - we can move forward with this and add the missing ones when we will get them

**Comment by xFreed0m** [comment]
@omercnet  missing logos added

**Comment by omercnet** [comment]
also added the sponsors to the main page

**Review by omercnet — APPROVED** [review]

**Pull request merged**
